# Generated by Django 5.2.8 on 2025-11-29 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OpenDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=200)),
                ('banner_text', models.TextField(help_text='Top banner message (e.g. ‘Sorry we have sold out!’)')),
                ('body_html', models.TextField(help_text='Main content in HTML (paragraphs, links, etc.)')),
                ('date', models.DateField(help_text='Date of the open day')),
                ('entry_from', models.CharField(help_text="e.g. '11am'", max_length=50)),
                ('last_entry', models.CharField(help_text="e.g. '4:30pm'", max_length=50)),
                ('ticket_url', models.URLField()),
                ('accessibility_note', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Open Day',
                'verbose_name_plural': 'Open Days',
            },
        ),
    ]
