# Generated by Django 5.2.8 on 2025-11-29 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('intro_text', models.TextField(help_text='Short intro/standfirst')),
                ('main_image', models.ImageField(blank=True, help_text='Main image for the article', null=True, upload_to='blog_main_images/')),
                ('body_html', models.TextField(help_text='Full body (HTML). Can contain images, embeds, etc.')),
                ('author', models.CharField(help_text='Display name of the author', max_length=100)),
                ('publish_date', models.DateField()),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-publish_date', '-created_at'],
            },
        ),
    ]
