# Generated by Django 5.2.8 on 2025-12-14 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='body_json',
            field=models.JSONField(default=dict, editable=False),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='body_html',
            field=models.TextField(help_text='Body content (rich text).'),
        ),
    ]
